### ISSUE TITLE
  java.lang.NullPointerException  in de.danielweisser.android.plaxosync.platform.ContactManager.makeGroupVisible

### ISSUE THREAD

**Issue by weisserd** [weisserd/Plaxo-Sync#5]
java.lang.NullPointerException
at de.danielweisser.android.plaxosync.platform.ContactManager.makeGroupVisible(ContactManager.java:284)
at de.danielweisser.android.plaxosync.authenticator.PlaxoAuthenticatorActivity.finishLogin(PlaxoAuthenticatorActivity.java:116)
at de.danielweisser.android.plaxosync.authenticator.PlaxoAuthenticatorActivity.onAuthenticationResult(PlaxoAuthenticatorActivity.java:165)
at de.danielweisser.android.plaxosync.client.PlaxoUtilities$3.run(PlaxoUtilities.java:152)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)

**Comment by weisserd** [comment]
The acquireContentProviderClient didn't work properly.
