### ISSUE TITLE
java.lang.NullPointerException at de.danielweisser.android.plaxosync.client.PlaxoUtilities.parseJSON

### ISSUE THREAD

**Issue by weisserd** [weisserd/Plaxo-Sync#7]
java.lang.NullPointerException
at de.danielweisser.android.plaxosync.client.PlaxoUtilities.parseJSON(PlaxoUtilities.java:231)
at de.danielweisser.android.plaxosync.client.PlaxoUtilities.fetchContacts(PlaxoUtilities.java:194)
at de.danielweisser.android.plaxosync.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:51)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

**Comment by weisserd** [comment]
should be fixed with new version
